"use client";
import { useQuery } from "@tanstack/react-query";
import { APIClient } from "@/api/client";
import { loadRuntimeConfig } from "@/api/config";
import { queryKeys } from "@/api/query-keys";
import type { NodeHealth } from "@/types/api";
import { ConfigError } from "@/components/config-error";
import { StatusBadge } from "@/components/status-badge";
export function DashboardRoute() {
  const result = loadRuntimeConfig(); const config = "config" in result ? result.config : null;
  const query = useQuery({ queryKey: queryKeys.health(config?.workspaceId ?? "unconfigured"), queryFn: ({ signal }) => new APIClient(config!).get<NodeHealth>("/api/v1/status", signal), enabled: config !== null });
  if (!config) return <ConfigError message={"error" in result ? result.error : "UI configuration is unavailable"} />;
  return <main className="app-shell"><aside className="sidebar"><p className="brand">ROUND<span>TABLE</span></p><p className="muted">Control plane</p><nav aria-label="Primary"><a className="active" href="/dashboard">Dashboard</a><a href="/proposals">Proposals</a><a href="/claims">Claims</a><a href="/transactions">Transactions</a><a href="/settings">Settings</a></nav></aside><section className="content"><header className="topbar"><div><p className="eyebrow">Workspace / {config.workspaceId}</p><h1>Control center</h1></div><span className="build">build {config.buildVersion}</span></header><section className="hero"><div><p className="eyebrow">Authoritative node status</p><h2>Governance at a glance</h2><p className="muted">Server state is loaded over REST and will be reconciled from the workspace event stream.</p></div>{query.isPending && <div className="skeleton card" aria-label="Loading status" />}{query.isError && <div className="card" role="alert"><StatusBadge status="error" /><p>Unable to reach the API.</p><button className="button secondary" onClick={() => query.refetch()}>Retry</button></div>}{query.data && <div className="card"><StatusBadge status={query.data.status} /><p className="metric">{Object.keys(query.data.components).length}</p><p className="muted">health components</p><time dateTime={query.data.time}>{query.data.time}</time></div>}</section>{query.data?.degraded_reasons?.length ? <section className="notice" role="status"><strong>Degraded:</strong> {query.data.degraded_reasons.join("; ")}</section> : null}<section className="grid" aria-label="Control center sections"><article className="panel"><p className="eyebrow">Live queue</p><h3>Proposals</h3><p className="metric">—</p><p className="muted">Select a workspace to load governed proposals.</p></article><article className="panel"><p className="eyebrow">Attention</p><h3>Human approvals</h3><p className="metric">—</p><p className="muted">No client-side completion is inferred.</p></article><article className="panel"><p className="eyebrow">Event stream</p><h3>Reconnection</h3><StatusBadge status="ready" /><p className="muted">Sequence-gap resync is reserved for the live-event feature.</p></article></section></section></main>;
}
