import type { ReactNode } from "react";

export function Panel({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rt-panel ${className}`}>{children}</section>; }
export function MetricCard({ label, value, detail }: { label: string; value: ReactNode; detail?: ReactNode }) { return <Panel className="rt-metric-card"><p className="rt-eyebrow">{label}</p><p className="rt-metric">{value}</p>{detail ? <p className="rt-muted">{detail}</p> : null}</Panel>; }
export function StatusPill({ status }: { status: string }) { return <span className={`rt-status rt-status-${status.toLowerCase().replaceAll(" ", "-")}`}><span aria-hidden="true">●</span> {status}</span>; }
export const StatusBadge = StatusPill;
export function EntityChip({ children, kind = "entity" }: { children: ReactNode; kind?: string }) { return <span className="rt-chip"><span className="rt-chip-kind">{kind}</span>{children}</span>; }
export function IconButton({ label, children, disabled = false, onClick }: { label: string; children: ReactNode; disabled?: boolean; onClick?: () => void }) { return <button className="rt-icon-button" type="button" aria-label={label} title={label} disabled={disabled} onClick={onClick}>{children}</button>; }
export function ToolbarButton({ children, disabled = false, onClick }: { children: ReactNode; disabled?: boolean; onClick?: () => void }) { return <button className="rt-toolbar-button" type="button" disabled={disabled} onClick={onClick}>{children}</button>; }
export function Tabs({ tabs, active }: { tabs: readonly { id: string; label: string }[]; active: string }) { return <nav className="rt-tabs" aria-label="Sections">{tabs.map(tab => <a className={tab.id === active ? "active" : ""} href={`#${tab.id}`} key={tab.id}>{tab.label}</a>)}</nav>; }
export function DenseTable({ headers, rows }: { headers: readonly string[]; rows: readonly (readonly ReactNode[])[] }) { return <div className="rt-table-wrap"><table className="rt-table"><thead><tr>{headers.map(header => <th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }
export function KeyValueList({ values }: { values: readonly { key: string; value: ReactNode }[] }) { return <dl className="rt-key-values">{values.map(item => <div key={item.key}><dt>{item.key}</dt><dd>{item.value}</dd></div>)}</dl>; }
export function EmptyState({ title, detail }: { title: string; detail: string }) { return <div className="rt-state"><h3>{title}</h3><p className="rt-muted">{detail}</p></div>; }
export function ErrorState({ title, detail, onRetry }: { title: string; detail: string; onRetry?: () => void }) { return <div className="rt-state rt-state-error" role="alert"><h3>{title}</h3><p className="rt-muted">{detail}</p>{onRetry ? <ToolbarButton onClick={onRetry}>Retry</ToolbarButton> : null}</div>; }
export function Skeleton({ width = "100%", height = 72 }: { width?: string; height?: number }) { return <div className="rt-skeleton" aria-hidden="true" style={{ width, height }} />; }
export function CodeSnippet({ children }: { children: ReactNode }) { return <pre className="rt-code"><code>{children}</code></pre>; }
export function DiffStat({ added, removed }: { added: number; removed: number }) { return <span className="rt-diff-stat"><span className="rt-diff-add">+{added}</span> <span className="rt-diff-remove">−{removed}</span></span>; }
export function ProgressMeter({ value, max = 100, label }: { value: number; max?: number; label: string }) { return <div className="rt-progress"><div className="rt-progress-label"><span>{label}</span><span>{value}/{max}</span></div><progress value={value} max={max}>{value}</progress></div>; }
export function HealthIndicator({ status, label }: { status: string; label: string }) { return <span className="rt-health"><span className={`rt-health-dot rt-health-${status}`} aria-hidden="true" />{label}: {status}</span>; }
